ARG BASE_IMAGE="kasmweb/core-kde:local"
FROM $BASE_IMAGE AS base_layer

USER root
RUN apt-get update && apt-get install -y tree strace fd-find
COPY ./src /tmp/theme-src/
RUN /tmp/theme-src/install-theme
COPY ./src/inside-docker/kde-tweaks-startup /dockerstartup/kde-tweaks-startup

RUN rm -rf /home/kasm-default-profile/.config

COPY ./dolphin_22.12.3-1+kasm_amd64.deb /tmp/dolphin.deb
COPY ./libdolphinvcs5_22.12.3-1+kasm_amd64.deb /tmp/libdolphin.deb
RUN apt-get update && apt-get install -y /tmp/*.deb

USER 1000

ENTRYPOINT ["/dockerstartup/kde-tweaks-startup"]
