#!/bin/bash

set -e

build_tweak_image() {
  docker build -t "$image" --build-arg "BASE_IMAGE=$1" -f dockerfile-kasm-kde-tweaks .
}

run_tweak_image() {
  docker run $volume_options \
    --rm -it --shm-size=512m -p 7901:6901 -e VNC_PW=password "$image"
}

set -x
image=kasmweb/kde-tweaks:local
volume_options="-v $PWD/kde-config/.config:/home/kasm-user/.config -v $PWD/kde-config/.local:/home/kasm-user/.local"
if [[ "$1" = "--pristine" || "$1" = "-p" ]]; then
  volume_options=
fi

build_tweak_image $1
run_tweak_image
